.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Johan Wermensjö <johanwermensjoe@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MEDIA-CLEANER 1 "October 26, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
media-cleaner \- cleans and sorts media files
.SH SYNOPSIS
.B media-cleaner
.RI [ options ]
[\fB\-movie-dir\fR \fIMOVIE_DIR\fR]
[\fB\-\-tv-dir\fR \fITV_DIR\fR]
[\fB\-\-config\fR \fICONFIG\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B media-cleaner
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBmedia-cleaner\fP is a program that cleans and sorts media files.
More specifically it formats names and sorts files into a predetermined
folder structure. The name format and file placement depends on the
type of file and what media library it belongs to. The two media libraries
that are supported are "tv-series" and "movies".
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.TP
.B \-s, \-\-safemode
Disables any file changes.
.TP
.B \-v, \-\-verbose
Enables verbose mode.
.TP
.B \-c, \-\-cron
Enables cron mode with extra log output.
.TP
.B \-f, \-\-force
Force clean and ignore torrent activity.
.TP
.B \-t, \-\-tv
Clean tv-series directory,
.TP
.B \-m, \-\-movie
Clean movie directory.
.TP
.B \-\-movie-dir =\fIMOVIE_DIR\fR
Path to movie directory.
.TP
.B \-\-tv-dir =\fITV_DIR\fR
Path to tv-series directory.
.TP
.B \-\-config =\fICONFIG\fR
Path to the yaml file containing media paths.
